steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'docker pull gcr.io/$PROJECT_ID/${REPO_NAME}-${BRANCH_NAME}:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/${REPO_NAME}-${BRANCH_NAME}:latest',
      '--cache-from', 'gcr.io/$PROJECT_ID/${REPO_NAME}-${BRANCH_NAME}:latest', '.'
    ]
timeout: 1800s
images:
  - 'gcr.io/$PROJECT_ID/${REPO_NAME}-${BRANCH_NAME}:latest'