steps:
  - name: node
    entrypoint: npm
    args: ['install']

  - name: gcr.io/cloud-builders/docker
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/${REPO_NAME}-${BRANCH_NAME}:latest',
      '--cache-from', 'gcr.io/$PROJECT_ID/${REPO_NAME}-${BRANCH_NAME}:latest', '.'
    ]
timeout: 1800s
images:
  - 'gcr.io/$PROJECT_ID/${REPO_NAME}-${BRANCH_NAME}:latest'