steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull gcr.io/$PROJECT_ID/${REPO_NAME}-${BRANCH_NAME}:latest || exit 0

  - name: gcr.io/cloud-builders/docker
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/${REPO_NAME}-${BRANCH_NAME}:${_TAG}',
      '-t', 'gcr.io/$PROJECT_ID/${REPO_NAME}-${BRANCH_NAME}:latest',
      '--cache-from', 'gcr.io/$PROJECT_ID/${REPO_NAME}-${BRANCH_NAME}:latest', '.'
    ]
timeout: 1800s
images:
  - 'gcr.io/$PROJECT_ID/${REPO_NAME}-${BRANCH_NAME}:${_TAG}'
  - 'gcr.io/$PROJECT_ID/${REPO_NAME}-${BRANCH_NAME}:latest'