version: '3'

services:
  api:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8081:8080"
      - "8082:4000"
#    volumes:
#      - .:/app