apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    name: api
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  replicas: 2
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - image: gcr.io/kustceramics/kust-ceramics-api-master:latest
          name: api
          ports:
            - containerPort: 8080
              name: api
          imagePullPolicy: Always